<a href="https://colab.research.google.com/github/Pavan-247/Files/blob/main/Assignment%202_prob_6b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns; sns.set()
import numpy as np
from sklearn import datasets
from sklearn.decomposition import PCA
import numpy as np

plt.style.use('classic')
%matplotlib inline

In [13]:
#from google.colab import files
#uploaded = files.upload()

Saving Boston_Building_Energy_Data_Ex_5p3 (1).xlsx to Boston_Building_Energy_Data_Ex_5p3 (1).xlsx


In [50]:
import requests as rq
from io import BytesIO


url = "https://github.com/Pavan-247/Files/blob/main/Boston_Building_Energy_Data_Ex_5p3%20(1).xlsx?raw=true"
data = rq.get(url).content
d = pd.read_excel(BytesIO(data))
d

Case                             PropertyType  FloorArea_ft_2  YearBuilt  \
0      1                         'Medical Office'           35036       1990   
1      2                                 'Office'           36865       1981   
2      3  'Hospital (General Medical & Surgical)'          865000       2008   
3      4                                  'Other'          291451       2010   
4      5                    'Multifamily Housing'            9568       1986   
5      6                         'Medical Office'          230000       1950   
6      7  'Hospital (General Medical & Surgical)'         2497517       1975   
7      8                                 'Office'           65016       1913   
8      9                    'Multifamily Housing'           25000       1891   
9     10                                 'Office'          180096       1920   
10    11              'Supermarket/Grocery Store'           18175       1978   
11    12                         'Medical Office'           56487       1918   
12    13                    'Multifamily Housing'           23803       1920   
13    14                            'K-12 School'           53270       1970   
14    15  'Hospital (General Medical & Surgical)'         2138279       1910   
15    16                    'Multifamily Housing'           12297       1988   
16    17  'Hospital (General Medical & Surgical)'          389552       1973   
17    18                    'Multifamily Housing'            7740       1985   
18    19                         'Medical Office'          353535       2000   
19    20                                  'Hotel'           27720       2002   

    ENERGYSTARScore  SiteEUI_kBtu_ft_2  
0                 1              365.2  
1                 1              472.0  
2                 1              486.9  
3                 5              401.2  
4                60              351.4  
5                50              332.7  
6                21              329.8  
7                 7              340.7  
8                 1              363.1  
9                 9              375.3  
10               24              335.3  
11                1              426.3  
12                1              520.3  
13                1              389.0  
14               28              331.5  
15                7              328.8  
16                2              316.5  
17               15              420.3  
18               24              341.0  
19                1              413.9

In [27]:
#import io
#d = pd.read_excel(io.BytesIO(uploaded['Boston_Building_Energy_Data_Ex_5p3 (1).xlsx']))
#d

Case                             PropertyType  FloorArea_ft_2  YearBuilt  \
0      1                         'Medical Office'           35036       1990   
1      2                                 'Office'           36865       1981   
2      3  'Hospital (General Medical & Surgical)'          865000       2008   
3      4                                  'Other'          291451       2010   
4      5                    'Multifamily Housing'            9568       1986   
5      6                         'Medical Office'          230000       1950   
6      7  'Hospital (General Medical & Surgical)'         2497517       1975   
7      8                                 'Office'           65016       1913   
8      9                    'Multifamily Housing'           25000       1891   
9     10                                 'Office'          180096       1920   
10    11              'Supermarket/Grocery Store'           18175       1978   
11    12                         'Medical Office'           56487       1918   
12    13                    'Multifamily Housing'           23803       1920   
13    14                            'K-12 School'           53270       1970   
14    15  'Hospital (General Medical & Surgical)'         2138279       1910   
15    16                    'Multifamily Housing'           12297       1988   
16    17  'Hospital (General Medical & Surgical)'          389552       1973   
17    18                    'Multifamily Housing'            7740       1985   
18    19                         'Medical Office'          353535       2000   
19    20                                  'Hotel'           27720       2002   

    ENERGYSTARScore  SiteEUI_kBtu_ft_2  
0                 1              365.2  
1                 1              472.0  
2                 1              486.9  
3                 5              401.2  
4                60              351.4  
5                50              332.7  
6                21              329.8  
7                 7              340.7  
8                 1              363.1  
9                 9              375.3  
10               24              335.3  
11                1              426.3  
12                1              520.3  
13                1              389.0  
14               28              331.5  
15                7              328.8  
16                2              316.5  
17               15              420.3  
18               24              341.0  
19                1              413.9

In [51]:
from sklearn.preprocessing import StandardScaler
features = ['YearBuilt','ENERGYSTARScore']
# Separating out the features
x = d.loc[:, features].values
# Standardizing the features
x = StandardScaler().fit_transform(x)
x

array([[ 0.72781445, -0.7211403 ],
       [ 0.48156144, -0.7211403 ],
       [ 1.22032046, -0.7211403 ],
       [ 1.27504335, -0.4807602 ],
       [ 0.61836866,  2.82446619],
       [-0.36664337,  2.22351593],
       [ 0.31739277,  0.4807602 ],
       [-1.37901684, -0.36057015],
       [-1.98096864, -0.7211403 ],
       [-1.18748673, -0.2403801 ],
       [ 0.3994771 ,  0.66104528],
       [-1.24220962, -0.7211403 ],
       [-1.18748673, -0.7211403 ],
       [ 0.18058554, -0.7211403 ],
       [-1.46110118,  0.90142538],
       [ 0.67309155, -0.36057015],
       [ 0.26266987, -0.66104528],
       [ 0.59100722,  0.12019005],
       [ 1.0014289 ,  0.66104528],
       [ 1.05615179, -0.7211403 ]])

In [52]:
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])
principalDf

principal component 1  principal component 2
0                0.004719              -1.024566
1               -0.169408              -0.850439
2                0.352974              -1.372820
3                0.561643              -1.241541
4                2.434452               1.559947
5                1.313007               1.831519
6                0.564379               0.115518
7               -1.230074               0.720151
8               -1.910680               0.890833
9               -1.009654               0.669706
10               0.749903               0.184957
11              -1.388298               0.368452
12              -1.349603               0.329757
13              -0.382230              -0.637616
14              -0.395751               1.670559
15               0.220986              -0.730909
16              -0.281694              -0.653165
17               0.502892              -0.332918
18               1.175547              -0.240688
19               0.236889              -1.256735

In [53]:
pca.components_

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [54]:
pca.explained_variance_ratio_


array([0.5263497, 0.4736503])

In [55]:
pca.explained_variance_

array([1.10810462, 0.99715854])